version: '3.8'

services:
  web:
    build: .
    container_name: php-web
    ports:
      - "8888:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: boarddb
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpw
    ports:
      - "3306:3306"